id: I2D2AD6D9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:39:25+00:00'
last_modified: '2022-06-10T08:49:24.918037+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS60395
  title: མན་ངག་རྫོགས་པ་ཆེན་པོའི་གནད་ཐོར་བུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0704':
      image_group_id: I1GS60397
      title: Volume 1 of man ngag rdzogs pa chen po'i gnad thor bu
      total_pages: 404
      order: 1
      base_file: 0704.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
